version: '3.4'

services:

    node:
        image: node:13-alpine
        working_dir: /openhex
        volumes:
            - .:/openhex

            # Used for deploy
            - ~/.ssh:/root/.ssh:ro
            - ~/.gitconfig:/root/.gitconfig:ro
        command: sleep 1000000000
        ports:
            - 3000:3000
